backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "resource"
    label: "Academic Resource"
    files:
      - file: "public/data/resource.json"
        label: "Academic Resource"
        name: "resource"
        fields:
          - { label: "Title", name: "header", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Updates", name: "updates", widget: "list", default: [] }
