backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "resource"
    label: "Academic Resource"
    label_singular: "Resource"
    folder: "public/data/resource"
    create: true
    extension: "json"
    format: "json"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
